### PR TITLE
Improve behaviour for messageUpdatedHandler

### PR DESCRIPTION
**Pull request by purefunctor**
This reworks the message handlers to improve the core re-execution flow. There shouldn't be much change behaviour-wise but I'm still looking for clarifications as discussed in the PureScript Discord:
* Should the original evaluation result be replaced by the new one?
* Instead of reactions, why not put the result emoji on the message body instead?

### CODE REVIEW

**Comment by i-am-the-slime** [comment]
Hey, thank you very much! Could you explain how the new behaviour differs from the old one in a few sentences? From a quick glance the countdown logic in the code isn't clear to me

**Comment by purefunctor** [comment]
What I've done is essentially localize when the client listens to `messageUpdate`; instead of having it enabled globally, I've instead opted into enabling it after the first call to `parseAndRun` and then having it be disabled by a 10-second timer. To summarize the steps in the user's perspective:

* User tells Royo to compile code, Royo sends the results
* Royo listens for any updates to the original message, giving up after 10 seconds
* If the user edits their message, Royo recompiles the code and sends new results
* Royo sets another 10 second countdown, and waits for more updates

This localization of the `messageUpdate` listener allows Royo to differentiate which edited message is the appropriate one to watch for, instead of having to react to every message edit that happens in the server.

For the chunkier explanation
---

1. When a new message is received and it mentions Royo, try to parse then run it.

2. After that, we can start the "re-evaluation" loop. First we create a reference to a `Fiber` that removes the `messageUpdate` listener after 10 seconds.
```purescript
        stopFR <- do
          stopF <- forkAff stopSession
          Effect.new stopF # liftEffect
...
          stopSession = do
            delay (Milliseconds 10_000.0)
            client # offMessageUpdate # liftEffect
```

3. We then tell our client to watch for message updates, and have `recvMessage` handle it for us
```purescript
        let recvMessage old new =
              when (msg.id == old.id && msg.id == new.id) do
                -- Kill countdown
                stopF_ <- Effect.read stopFR # liftEffect
                killFiber (error "messageHandler: reset timer") stopF_

                -- Renew countdown
                stopF <- forkAff stopSession
                Effect.write stopF stopFR # liftEffect

                parseAndRun new

        client # onMessageUpdate (launchAff_ `map map map` recvMessage) # liftEffect
```
What `recvMessage` essentially does is:
* Check whether the id of edited message (`old`/`new`) matches that of the original one (`msg`) that was sent:
* Get the current countdown `Fiber` from `stopFR` and kill it
* Create a new countdown `Fiber` and store it inside of `stopFR`

**Comment by i-am-the-slime** [comment]
Thanks for the explanation, it's good that I asked, because I don't quite understand. Does this change mean that the bot won't recompile code that is edited more than 10 seconds after it was originally posted? 

What would be the motivation for that? I don't think listening to every message update is too bad, because we already listen for every new message which I would think are an order of magnitude more than updates. 

I'm a big wary of the complexity introduced by the timer, but I don't want to gatekeep too much either.

Am I missing something?

**Comment by purefunctor** [comment]
> Does this change mean that the bot won't recompile code that is edited more than 10 seconds after it was originally posted? 

That's correct

> What would be the motivation for that?

Perhaps I gave a bit too much foresight into this, but the primary motivation is to prevent abuse from old code-blocks being edited, and executing not-so-nice code that can be a bit of a pain point for the Moderators to track down. That said, this is _very_ unlikely to happen.

> I don't think listening to every message update is too bad, because we already listen for every new message which I would think are an order of magnitude more than updates.

That is true...

> I'm a big wary of the complexity introduced by the timer, but I don't want to gatekeep too much either.

In hindsight I personally don't like this solution that I wrote as well, if anything, that big wall of text above should be an indicator ><

We could probably work with the replies suggestion as well. If we still want to have some sort of timeout then perhaps we can use timestamps for that.

**Comment by purefunctor** [comment]
Okay! This set of changes should be a lot simpler, no fancy timers and all that jazz.

I only put the `isMention` constraint on `messageUpdatedHandler` to stop it from erroneously responding towards non-code-evaluation mentions to Royo. If we need some sort of re-eval timeout then we can just pull the `createdTimestamp` and `editedTimestamp` of the messages and compare them.

On another note, could we make it so that the bot ID isn't static? We can pull it from the `Client` object then delegate the scanning to the `Message` object. If need be, we can fall back to a static client ID.

**Review by i-am-the-slime — APPROVED** [review]

**Pull request merged**
